-- MySQL Script generated by MySQL Workbench
-- Wed Oct  1 17:06:02 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Table `tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tb_usuario` (
  `usu_id` INT NOT NULL AUTO_INCREMENT,
  `usu_nome` VARCHAR(100) NULL DEFAULT NULL,
  `usu_email` VARCHAR(100) NULL DEFAULT NULL,
  `usu_senha` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`usu_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tb_sala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tb_sala` (
  `sal_id` INT NOT NULL AUTO_INCREMENT,
  `sal_nome` VARCHAR(200) NULL DEFAULT NULL,
  `usu_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`sal_id`),
  INDEX `fk_sala_usuario_idx` (`usu_id` ASC) VISIBLE,
  CONSTRAINT `fk_sala_usuario`
    FOREIGN KEY (`usu_id`)
    REFERENCES `tb_usuario` (`usu_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tb_participante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tb_participante` (
  `par_id` INT NOT NULL AUTO_INCREMENT,
  `par_dtentrada` DATETIME NULL DEFAULT NULL,
  `par_dtsaida` DATETIME NULL DEFAULT NULL,
  `par_ordem` INT NULL,
  `par_saldo` DECIMAL(10,2) NULL,
  `sal_id` INT NULL DEFAULT NULL,
  `usu_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`par_id`),
  INDEX `fk_participante_usuario` (`usu_id` ASC) VISIBLE,
  INDEX `fk_participante_sala` (`sal_id` ASC) VISIBLE,
  CONSTRAINT `fk_participante_sala`
    FOREIGN KEY (`sal_id`)
    REFERENCES `tb_sala` (`sal_id`),
  CONSTRAINT `fk_participante_usuario`
    FOREIGN KEY (`usu_id`)
    REFERENCES `tb_usuario` (`usu_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tb_rodada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tb_rodada` (
  `rod_id` INT NOT NULL AUTO_INCREMENT,
  `rod_codigobaralho` VARCHAR(50) NULL DEFAULT NULL,
  `rod_dtinicio` DATETIME NULL DEFAULT NULL,
  `rod_dtfim` DATETIME NULL,
  `sal_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`rod_id`),
  INDEX `fk_rodada_sala_idx` (`sal_id` ASC) VISIBLE,
  CONSTRAINT `fk_rodada_sala`
    FOREIGN KEY (`sal_id`)
    REFERENCES `tb_sala` (`sal_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;



-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tb_aposta` (
  `apo_id` INT NOT NULL AUTO_INCREMENT,
  `apo_valor` DECIMAL(10,2) NULL,
  `par_id` INT NULL,
  `rod_id` INT NULL,
  PRIMARY KEY (`apo_id`),
  INDEX `fk_aposta_participante_idx` (`par_id` ASC) VISIBLE,
  INDEX `fk_aposta_rodada_idx` (`rod_id` ASC) VISIBLE,
  CONSTRAINT `fk_aposta_participante`
    FOREIGN KEY (`par_id`)
    REFERENCES `tb_participante` (`par_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aposta_rodada`
    FOREIGN KEY (`rod_id`)
    REFERENCES `tb_rodada` (`rod_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tb_turno` (
  `tur_id` INT NOT NULL AUTO_INCREMENT,
  `tur_somacartas` INT NULL,
  `tur_status` ENUM("Jogando", "Estourou", "Ganhou", "Perdeu") NULL,
  `par_id` INT NULL,
  `rod_id` INT NULL,
  PRIMARY KEY (`tur_id`),
  INDEX `fk_turno_participante_idx` (`par_id` ASC) VISIBLE,
  INDEX `fk_turno_rodada_idx` (`rod_id` ASC) VISIBLE,
  CONSTRAINT `fk_turno_participante`
    FOREIGN KEY (`par_id`)
    REFERENCES `tb_participante` (`par_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turno_rodada`
    FOREIGN KEY (`rod_id`)
    REFERENCES `tb_rodada` (`rod_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `tb_carta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tb_carta` (
  `car_id` INT NOT NULL AUTO_INCREMENT,
  `car_codigo` VARCHAR(10) NULL DEFAULT NULL,
  `car_imagem` VARCHAR(200) NULL DEFAULT NULL,
  `car_ordem` INT NULL,
  `car_visivel` ENUM('S', 'N') NULL,
  `car_valor` INT NULL DEFAULT NULL,
  `car_naipe` VARCHAR(20) NULL DEFAULT NULL,
  `par_id` INT NULL DEFAULT NULL,
  `rod_id` INT NULL DEFAULT NULL,
  INDEX `fk_carta_participante_idx` (`par_id` ASC) VISIBLE,
  INDEX `fk_carta_rodada_idx` (`rod_id` ASC) VISIBLE,
  PRIMARY KEY (`car_id`),
  CONSTRAINT `fk_carta_rodada`
    FOREIGN KEY (`rod_id`)
    REFERENCES `tb_rodada` (`rod_id`),
  CONSTRAINT `fk_carta_participante`
    FOREIGN KEY (`par_id`)
    REFERENCES `tb_participante` (`par_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

